# Custom Language File for Launcher Customizer

[ejs.app]
title = "RevixMC Launcher"

[ejs.landing]
mediaGitHubURL = "#"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.revixmc.xyz"

[ejs.settings]
sourceGithubLink = "#"
supportLink = "#"

[ejs.welcome]
welcomeHeader = "WELCOME TO REVIXMC"
welcomeDescription = "Copyright © 2025 RevixMC"
welcomeDescCTA = ""
